config/routes.rb
Rails.application.routes.draw do
  root "products#index"

  get "/products", to: "products#index"

  get "/products/:id", to: "products#reviews", as: 'reviews'

  post "/products/submit-review", to: "products#submit_review", as: 'submit_review'

  get "/products/info/:id", to: "products#product_info", as: 'product_reviews'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  validates :title, presence: true
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  validates :stars, :inclusion => [0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def reviews
    @product = Product.find(params[:id])
  end

  def submit_review
    stars = params[:stars]
    body = params[:body]
    product_id = params[:product_id]
    rating = Review.new(stars: stars, body: body, product_id: product_id)
    if rating.save
      ActionCable.server.broadcast("reviews_info", { body: "update" })
      render json: rating, status: :created
    else
      render json: rating.errors, status: :unprocessable_entity
    end
  end

  def product_info
    product = Product.find(params[:id])
    average = Review.where(product_id: product.id).average(:stars)
    if average then
      rating_average = average.round(2)
    else
      rating_average = 0
    end
    reviews = product.reviews.order(created_at: :desc)
    reviews_json = []
    reviews.each {|r|
      reviews_json.append({
        "stars": r.stars,
        "body": r.body
      })
    }
    result = {
      "title": product.title,
      "rating_average": rating_average,
      "reviews": reviews_json
    }
    render json: result, status: :ok
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def print_stars(num)
    num = num.to_int
    stars_str = ""
    if num > 5 then
      num = 5
    end
    num.times do
      stars_str += render("full_star")
    end
    (5 - num).times do
      stars_str += render("empty_star")
    end
    stars_str.html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Products</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap" rel="stylesheet"> 
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_empty_star.html.erb
<!-- Based on Font Awesome -->
<svg class="svg-inline--fa fa-star fa-w-18" aria-hidden="true" focusable="false" data-prefix="fa" data-icon="star" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512" data-fa-i2svg=""><path fill="#e0e0e0" d="M259.3 17.8L194 150.2 47.9 171.5c-26.2 3.8-36.7 36.1-17.7 54.6l105.7 103-25 145.5c-4.5 26.3 23.2 46 46.4 33.7L288 439.6l130.7 68.7c23.2 12.2 50.9-7.4 46.4-33.7l-25-145.5 105.7-103c19-18.5 8.5-50.8-17.7-54.6L382 150.2 316.7 17.8c-11.7-23.6-45.6-23.9-57.4 0z"></path></svg>

app/views/products/_full_star.html.erb
<!-- Based on Font Awesome -->
<svg class="svg-inline--fa fa-star fa-w-18" aria-hidden="true" focusable="false" data-prefix="fa" data-icon="star" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512" data-fa-i2svg=""><path fill="currentColor" d="M259.3 17.8L194 150.2 47.9 171.5c-26.2 3.8-36.7 36.1-17.7 54.6l105.7 103-25 145.5c-4.5 26.3 23.2 46 46.4 33.7L288 439.6l130.7 68.7c23.2 12.2 50.9-7.4 46.4-33.7l-25-145.5 105.7-103c19-18.5 8.5-50.8-17.7-54.6L382 150.2 316.7 17.8c-11.7-23.6-45.6-23.9-57.4 0z"></path></svg>

app/views/products/index.html.erb
<div class="container">
  <div class="content">
    <h1>Products</h1>
    <ul>
      <% @products.each do |product| %>
        <li><%= link_to product.title, reviews_path(product.id) %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/products/reviews.html.erb
<div id="root">
</div>

<div id="product_id" style="display:none;">
  <%= @product.id %>
</div>

<%= hidden_field_tag :authenticity_token, form_authenticity_token %>

<%= javascript_pack_tag 'reviews' %>